stateDiagram-v2
    [*] --> TilingNoneCompressionNone : ImageWriteParam ImageWriteParam([Locale locale])

    TilingNoneCompressionNone --> TilingNoneCompressionNone : boolean canWriteTiles()
    TilingNoneCompressionNone --> TilingNoneCompressionNone : boolean canOffsetTiles()
    TilingNoneCompressionNone --> TilingNoneCompressionNone : boolean canWriteProgressive()
    TilingNoneCompressionNone --> TilingNoneCompressionNone : boolean canWriteCompressed()
    TilingNoneCompressionNone --> TilingNoneCompressionNone : Locale getLocale()
    TilingNoneCompressionNone --> TilingNoneCompressionNone : int getTilingMode()
    TilingNoneCompressionNone --> TilingNoneCompressionNone : Dimension[] getPreferredTileSizes()
    TilingNoneCompressionNone --> TilingNoneCompressionNone : int getProgressiveMode()
    TilingNoneCompressionNone --> TilingNoneCompressionNone : void setProgressiveMode([int mode])
    TilingNoneCompressionNone --> TilingNoneCompressionNone : int getCompressionMode()
    TilingNoneCompressionNone --> TilingNoneCompressionNone : String[] getCompressionTypes()
    TilingNoneCompressionNone --> TilingExplicitCompressionNone : void setTilingMode([int mode])
    TilingNoneCompressionNone --> TilingNoneCompressionExplicit : void setCompressionMode([int mode])

    TilingNoneCompressionExplicit --> TilingNoneCompressionExplicit : boolean canWriteTiles()
    TilingNoneCompressionExplicit --> TilingNoneCompressionExplicit : boolean canOffsetTiles()
    TilingNoneCompressionExplicit --> TilingNoneCompressionExplicit : boolean canWriteProgressive()
    TilingNoneCompressionExplicit --> TilingNoneCompressionExplicit : boolean canWriteCompressed()
    TilingNoneCompressionExplicit --> TilingNoneCompressionExplicit : Locale getLocale()
    TilingNoneCompressionExplicit --> TilingNoneCompressionExplicit : int getTilingMode()
    TilingNoneCompressionExplicit --> TilingNoneCompressionExplicit : Dimension[] getPreferredTileSizes()
    TilingNoneCompressionExplicit --> TilingNoneCompressionExplicit : int getProgressiveMode()
    TilingNoneCompressionExplicit --> TilingNoneCompressionExplicit : void setProgressiveMode([int mode])
    TilingNoneCompressionExplicit --> TilingNoneCompressionExplicit : int getCompressionMode()
    TilingNoneCompressionExplicit --> TilingNoneCompressionExplicit : String[] getCompressionTypes()
    TilingNoneCompressionExplicit --> TilingNoneCompressionExplicit : void unsetCompression()
    TilingNoneCompressionExplicit --> TilingExplicitCompressionExplicit : void setTilingMode([int mode])
    TilingNoneCompressionExplicit --> TilingNoneCompressionNone : void setCompressionMode([int mode])
    TilingNoneCompressionExplicit --> TilingNoneCompressionExplicitWithType : void setCompressionType([String compressionType])

    TilingNoneCompressionExplicitWithType --> TilingNoneCompressionExplicitWithType : boolean canWriteTiles()
    TilingNoneCompressionExplicitWithType --> TilingNoneCompressionExplicitWithType : boolean canOffsetTiles()
    TilingNoneCompressionExplicitWithType --> TilingNoneCompressionExplicitWithType : boolean canWriteProgressive()
    TilingNoneCompressionExplicitWithType --> TilingNoneCompressionExplicitWithType : boolean canWriteCompressed()
    TilingNoneCompressionExplicitWithType --> TilingNoneCompressionExplicitWithType : Locale getLocale()
    TilingNoneCompressionExplicitWithType --> TilingNoneCompressionExplicitWithType : int getTilingMode()
    TilingNoneCompressionExplicitWithType --> TilingNoneCompressionExplicitWithType : Dimension[] getPreferredTileSizes()
    TilingNoneCompressionExplicitWithType --> TilingNoneCompressionExplicitWithType : int getProgressiveMode()
    TilingNoneCompressionExplicitWithType --> TilingNoneCompressionExplicitWithType : void setProgressiveMode([int mode])
    TilingNoneCompressionExplicitWithType --> TilingNoneCompressionExplicitWithType : int getCompressionMode()
    TilingNoneCompressionExplicitWithType --> TilingNoneCompressionExplicitWithType : String[] getCompressionTypes()
    TilingNoneCompressionExplicitWithType --> TilingNoneCompressionExplicitWithType : String getCompressionType()
    TilingNoneCompressionExplicitWithType --> TilingNoneCompressionExplicitWithType : String getLocalizedCompressionTypeName()
    TilingNoneCompressionExplicitWithType --> TilingNoneCompressionExplicitWithType : boolean isCompressionLossless()
    TilingNoneCompressionExplicitWithType --> TilingNoneCompressionExplicitWithType : void setCompressionQuality([float quality])
    TilingNoneCompressionExplicitWithType --> TilingNoneCompressionExplicitWithType : float getCompressionQuality()
    TilingNoneCompressionExplicitWithType --> TilingNoneCompressionExplicitWithType : float getBitRate([float quality])
    TilingNoneCompressionExplicitWithType --> TilingNoneCompressionExplicitWithType : String[] getCompressionQualityDescriptions()
    TilingNoneCompressionExplicitWithType --> TilingNoneCompressionExplicitWithType : float[] getCompressionQualityValues()
    TilingNoneCompressionExplicitWithType --> TilingExplicitCompressionExplicitWithType : void setTilingMode([int mode])
    TilingNoneCompressionExplicitWithType --> TilingNoneCompressionNone : void setCompressionMode([int mode])
    TilingNoneCompressionExplicitWithType --> TilingNoneCompressionExplicit : void unsetCompression()
    TilingNoneCompressionExplicitWithType --> TilingNoneCompressionExplicit : void setCompressionType([String compressionType])

    TilingExplicitCompressionNone --> TilingExplicitCompressionNone : boolean canWriteTiles()
    TilingExplicitCompressionNone --> TilingExplicitCompressionNone : boolean canOffsetTiles()
    TilingExplicitCompressionNone --> TilingExplicitCompressionNone : boolean canWriteProgressive()
    TilingExplicitCompressionNone --> TilingExplicitCompressionNone : boolean canWriteCompressed()
    TilingExplicitCompressionNone --> TilingExplicitCompressionNone : Locale getLocale()
    TilingExplicitCompressionNone --> TilingExplicitCompressionNone : int getTilingMode()
    TilingExplicitCompressionNone --> TilingExplicitCompressionNone : Dimension[] getPreferredTileSizes()
    TilingExplicitCompressionNone --> TilingExplicitCompressionNone : int getProgressiveMode()
    TilingExplicitCompressionNone --> TilingExplicitCompressionNone : void setProgressiveMode([int mode])
    TilingExplicitCompressionNone --> TilingExplicitCompressionNone : int getCompressionMode()
    TilingExplicitCompressionNone --> TilingExplicitCompressionNone : String[] getCompressionTypes()
    TilingExplicitCompressionNone --> TilingExplicitCompressionNone : void unsetTiling()
    TilingExplicitCompressionNone --> TilingNoneCompressionNone : void setTilingMode([int mode])
    TilingExplicitCompressionNone --> TilingExplicitWithParamsCompressionNone : void setTiling([int tileWidth], [int tileHeight], [int tileGridXOffset], [int tileGridYOffset])
    TilingExplicitCompressionNone --> TilingExplicitCompressionExplicit : void setCompressionMode([int mode])

    TilingExplicitCompressionExplicit --> TilingExplicitCompressionExplicit : boolean canWriteTiles()
    TilingExplicitCompressionExplicit --> TilingExplicitCompressionExplicit : boolean canOffsetTiles()
    TilingExplicitCompressionExplicit --> TilingExplicitCompressionExplicit : boolean canWriteProgressive()
    TilingExplicitCompressionExplicit --> TilingExplicitCompressionExplicit : boolean canWriteCompressed()
    TilingExplicitCompressionExplicit --> TilingExplicitCompressionExplicit : Locale getLocale()
    TilingExplicitCompressionExplicit --> TilingExplicitCompressionExplicit : int getTilingMode()
    TilingExplicitCompressionExplicit --> TilingExplicitCompressionExplicit : Dimension[] getPreferredTileSizes()
    TilingExplicitCompressionExplicit --> TilingExplicitCompressionExplicit : int getProgressiveMode()
    TilingExplicitCompressionExplicit --> TilingExplicitCompressionExplicit : void setProgressiveMode([int mode])
    TilingExplicitCompressionExplicit --> TilingExplicitCompressionExplicit : int getCompressionMode()
    TilingExplicitCompressionExplicit --> TilingExplicitCompressionExplicit : String[] getCompressionTypes()
    TilingExplicitCompressionExplicit --> TilingExplicitCompressionExplicit : void unsetTiling()
    TilingExplicitCompressionExplicit --> TilingExplicitCompressionExplicit : void unsetCompression()
    TilingExplicitCompressionExplicit --> TilingNoneCompressionExplicit : void setTilingMode([int mode])
    TilingExplicitCompressionExplicit --> TilingExplicitWithParamsCompressionExplicit : void setTiling([int tileWidth], [int tileHeight], [int tileGridXOffset], [int tileGridYOffset])
    TilingExplicitCompressionExplicit --> TilingExplicitCompressionNone : void setCompressionMode([int mode])
    TilingExplicitCompressionExplicit --> TilingExplicitCompressionExplicitWithType : void setCompressionType([String compressionType])

    TilingExplicitCompressionExplicitWithType --> TilingExplicitCompressionExplicitWithType : boolean canWriteTiles()
    TilingExplicitCompressionExplicitWithType --> TilingExplicitCompressionExplicitWithType : boolean canOffsetTiles()
    TilingExplicitCompressionExplicitWithType --> TilingExplicitCompressionExplicitWithType : boolean canWriteProgressive()
    TilingExplicitCompressionExplicitWithType --> TilingExplicitCompressionExplicitWithType : boolean canWriteCompressed()
    TilingExplicitCompressionExplicitWithType --> TilingExplicitCompressionExplicitWithType : Locale getLocale()
    TilingExplicitCompressionExplicitWithType --> TilingExplicitCompressionExplicitWithType : int getTilingMode()
    TilingExplicitCompressionExplicitWithType --> TilingExplicitCompressionExplicitWithType : Dimension[] getPreferredTileSizes()
    TilingExplicitCompressionExplicitWithType --> TilingExplicitCompressionExplicitWithType : int getProgressiveMode()
    TilingExplicitCompressionExplicitWithType --> TilingExplicitCompressionExplicitWithType : void setProgressiveMode([int mode])
    TilingExplicitCompressionExplicitWithType --> TilingExplicitCompressionExplicitWithType : int getCompressionMode()
    TilingExplicitCompressionExplicitWithType --> TilingExplicitCompressionExplicitWithType : String[] getCompressionTypes()
    TilingExplicitCompressionExplicitWithType --> TilingExplicitCompressionExplicitWithType : void unsetTiling()
    TilingExplicitCompressionExplicitWithType --> TilingExplicitCompressionExplicitWithType : String getCompressionType()
    TilingExplicitCompressionExplicitWithType --> TilingExplicitCompressionExplicitWithType : String getLocalizedCompressionTypeName()
    TilingExplicitCompressionExplicitWithType --> TilingExplicitCompressionExplicitWithType : boolean isCompressionLossless()
    TilingExplicitCompressionExplicitWithType --> TilingExplicitCompressionExplicitWithType : void setCompressionQuality([float quality])
    TilingExplicitCompressionExplicitWithType --> TilingExplicitCompressionExplicitWithType : float getCompressionQuality()
    TilingExplicitCompressionExplicitWithType --> TilingExplicitCompressionExplicitWithType : float getBitRate([float quality])
    TilingExplicitCompressionExplicitWithType --> TilingExplicitCompressionExplicitWithType : String[] getCompressionQualityDescriptions()
    TilingExplicitCompressionExplicitWithType --> TilingExplicitCompressionExplicitWithType : float[] getCompressionQualityValues()
    TilingExplicitCompressionExplicitWithType --> TilingNoneCompressionExplicitWithType : void setTilingMode([int mode])
    TilingExplicitCompressionExplicitWithType --> TilingExplicitWithParamsCompressionExplicitWithType : void setTiling([int tileWidth], [int tileHeight], [int tileGridXOffset], [int tileGridYOffset])
    TilingExplicitCompressionExplicitWithType --> TilingExplicitCompressionNone : void setCompressionMode([int mode])
    TilingExplicitCompressionExplicitWithType --> TilingExplicitCompressionExplicit : void unsetCompression()
    TilingExplicitCompressionExplicitWithType --> TilingExplicitCompressionExplicit : void setCompressionType([String compressionType])

    TilingExplicitWithParamsCompressionNone --> TilingExplicitWithParamsCompressionNone : boolean canWriteTiles()
    TilingExplicitWithParamsCompressionNone --> TilingExplicitWithParamsCompressionNone : boolean canOffsetTiles()
    TilingExplicitWithParamsCompressionNone --> TilingExplicitWithParamsCompressionNone : boolean canWriteProgressive()
    TilingExplicitWithParamsCompressionNone --> TilingExplicitWithParamsCompressionNone : boolean canWriteCompressed()
    TilingExplicitWithParamsCompressionNone --> TilingExplicitWithParamsCompressionNone : Locale getLocale()
    TilingExplicitWithParamsCompressionNone --> TilingExplicitWithParamsCompressionNone : int getTilingMode()
    TilingExplicitWithParamsCompressionNone --> TilingExplicitWithParamsCompressionNone : Dimension[] getPreferredTileSizes()
    TilingExplicitWithParamsCompressionNone --> TilingExplicitWithParamsCompressionNone : int getProgressiveMode()
    TilingExplicitWithParamsCompressionNone --> TilingExplicitWithParamsCompressionNone : void setProgressiveMode([int mode])
    TilingExplicitWithParamsCompressionNone --> TilingExplicitWithParamsCompressionNone : int getCompressionMode()
    TilingExplicitWithParamsCompressionNone --> TilingExplicitWithParamsCompressionNone : String[] getCompressionTypes()
    TilingExplicitWithParamsCompressionNone --> TilingExplicitWithParamsCompressionNone : int getTileWidth()
    TilingExplicitWithParamsCompressionNone --> TilingExplicitWithParamsCompressionNone : int getTileHeight()
    TilingExplicitWithParamsCompressionNone --> TilingExplicitWithParamsCompressionNone : int getTileGridXOffset()
    TilingExplicitWithParamsCompressionNone --> TilingExplicitWithParamsCompressionNone : int getTileGridYOffset()
    TilingExplicitWithParamsCompressionNone --> TilingExplicitWithParamsCompressionNone : void setTiling([int tileWidth], [int tileHeight], [int tileGridXOffset], [int tileGridYOffset])
    TilingExplicitWithParamsCompressionNone --> TilingNoneCompressionNone : void setTilingMode([int mode])
    TilingExplicitWithParamsCompressionNone --> TilingExplicitCompressionNone : void unsetTiling()
    TilingExplicitWithParamsCompressionNone --> TilingExplicitWithParamsCompressionExplicit : void setCompressionMode([int mode])

    TilingExplicitWithParamsCompressionExplicit --> TilingExplicitWithParamsCompressionExplicit : boolean canWriteTiles()
    TilingExplicitWithParamsCompressionExplicit --> TilingExplicitWithParamsCompressionExplicit : boolean canOffsetTiles()
    TilingExplicitWithParamsCompressionExplicit --> TilingExplicitWithParamsCompressionExplicit : boolean canWriteProgressive()
    TilingExplicitWithParamsCompressionExplicit --> TilingExplicitWithParamsCompressionExplicit : boolean canWriteCompressed()
    TilingExplicitWithParamsCompressionExplicit --> TilingExplicitWithParamsCompressionExplicit : Locale getLocale()
    TilingExplicitWithParamsCompressionExplicit --> TilingExplicitWithParamsCompressionExplicit : int getTilingMode()
    TilingExplicitWithParamsCompressionExplicit --> TilingExplicitWithParamsCompressionExplicit : Dimension[] getPreferredTileSizes()
    TilingExplicitWithParamsCompressionExplicit --> TilingExplicitWithParamsCompressionExplicit : int getProgressiveMode()
    TilingExplicitWithParamsCompressionExplicit --> TilingExplicitWithParamsCompressionExplicit : void setProgressiveMode([int mode])
    TilingExplicitWithParamsCompressionExplicit --> TilingExplicitWithParamsCompressionExplicit : int getCompressionMode()
    TilingExplicitWithParamsCompressionExplicit --> TilingExplicitWithParamsCompressionExplicit : String[] getCompressionTypes()
    TilingExplicitWithParamsCompressionExplicit --> TilingExplicitWithParamsCompressionExplicit : int getTileWidth()
    TilingExplicitWithParamsCompressionExplicit --> TilingExplicitWithParamsCompressionExplicit : int getTileHeight()
    TilingExplicitWithParamsCompressionExplicit --> TilingExplicitWithParamsCompressionExplicit : int getTileGridXOffset()
    TilingExplicitWithParamsCompressionExplicit --> TilingExplicitWithParamsCompressionExplicit : int getTileGridYOffset()
    TilingExplicitWithParamsCompressionExplicit --> TilingExplicitWithParamsCompressionExplicit : void setTiling([int tileWidth], [int tileHeight], [int tileGridXOffset], [int tileGridYOffset])
    TilingExplicitWithParamsCompressionExplicit --> TilingExplicitWithParamsCompressionExplicit : void unsetCompression()
    TilingExplicitWithParamsCompressionExplicit --> TilingNoneCompressionExplicit : void setTilingMode([int mode])
    TilingExplicitWithParamsCompressionExplicit --> TilingExplicitCompressionExplicit : void unsetTiling()
    TilingExplicitWithParamsCompressionExplicit --> TilingExplicitWithParamsCompressionNone : void setCompressionMode([int mode])
    TilingExplicitWithParamsCompressionExplicit --> TilingExplicitWithParamsCompressionExplicitWithType : void setCompressionType([String compressionType])

    TilingExplicitWithParamsCompressionExplicitWithType --> TilingExplicitWithParamsCompressionExplicitWithType : boolean canWriteTiles()
    TilingExplicitWithParamsCompressionExplicitWithType --> TilingExplicitWithParamsCompressionExplicitWithType : boolean canOffsetTiles()
    TilingExplicitWithParamsCompressionExplicitWithType --> TilingExplicitWithParamsCompressionExplicitWithType : boolean canWriteProgressive()
    TilingExplicitWithParamsCompressionExplicitWithType --> TilingExplicitWithParamsCompressionExplicitWithType : boolean canWriteCompressed()
    TilingExplicitWithParamsCompressionExplicitWithType --> TilingExplicitWithParamsCompressionExplicitWithType : Locale getLocale()
    TilingExplicitWithParamsCompressionExplicitWithType --> TilingExplicitWithParamsCompressionExplicitWithType : int getTilingMode()
    TilingExplicitWithParamsCompressionExplicitWithType --> TilingExplicitWithParamsCompressionExplicitWithType : Dimension[] getPreferredTileSizes()
    TilingExplicitWithParamsCompressionExplicitWithType --> TilingExplicitWithParamsCompressionExplicitWithType : int getProgressiveMode()
    TilingExplicitWithParamsCompressionExplicitWithType --> TilingExplicitWithParamsCompressionExplicitWithType : void setProgressiveMode([int mode])
    TilingExplicitWithParamsCompressionExplicitWithType --> TilingExplicitWithParamsCompressionExplicitWithType : int getCompressionMode()
    TilingExplicitWithParamsCompressionExplicitWithType --> TilingExplicitWithParamsCompressionExplicitWithType : String[] getCompressionTypes()
    TilingExplicitWithParamsCompressionExplicitWithType --> TilingExplicitWithParamsCompressionExplicitWithType : int getTileWidth()
    TilingExplicitWithParamsCompressionExplicitWithType --> TilingExplicitWithParamsCompressionExplicitWithType : int getTileHeight()
    TilingExplicitWithParamsCompressionExplicitWithType --> TilingExplicitWithParamsCompressionExplicitWithType : int getTileGridXOffset()
    TilingExplicitWithParamsCompressionExplicitWithType --> TilingExplicitWithParamsCompressionExplicitWithType : int getTileGridYOffset()
    TilingExplicitWithParamsCompressionExplicitWithType --> TilingExplicitWithParamsCompressionExplicitWithType : void setTiling([int tileWidth], [int tileHeight], [int tileGridXOffset], [int tileGridYOffset])
    TilingExplicitWithParamsCompressionExplicitWithType --> TilingExplicitWithParamsCompressionExplicitWithType : String getCompressionType()
    TilingExplicitWithParamsCompressionExplicitWithType --> TilingExplicitWithParamsCompressionExplicitWithType : String getLocalizedCompressionTypeName()
    TilingExplicitWithParamsCompressionExplicitWithType --> TilingExplicitWithParamsCompressionExplicitWithType : boolean isCompressionLossless()
    TilingExplicitWithParamsCompressionExplicitWithType --> TilingExplicitWithParamsCompressionExplicitWithType : void setCompressionQuality([float quality])
    TilingExplicitWithParamsCompressionExplicitWithType --> TilingExplicitWithParamsCompressionExplicitWithType : float getCompressionQuality()
    TilingExplicitWithParamsCompressionExplicitWithType --> TilingExplicitWithParamsCompressionExplicitWithType : float getBitRate([float quality])
    TilingExplicitWithParamsCompressionExplicitWithType --> TilingExplicitWithParamsCompressionExplicitWithType : String[] getCompressionQualityDescriptions()
    TilingExplicitWithParamsCompressionExplicitWithType --> TilingExplicitWithParamsCompressionExplicitWithType : float[] getCompressionQualityValues()
    TilingExplicitWithParamsCompressionExplicitWithType --> TilingNoneCompressionExplicitWithType : void setTilingMode([int mode])
    TilingExplicitWithParamsCompressionExplicitWithType --> TilingExplicitCompressionExplicitWithType : void unsetTiling()
    TilingExplicitWithParamsCompressionExplicitWithType --> TilingExplicitWithParamsCompressionNone : void setCompressionMode([int mode])
    TilingExplicitWithParamsCompressionExplicitWithType --> TilingExplicitWithParamsCompressionExplicit : void unsetCompression()
    TilingExplicitWithParamsCompressionExplicitWithType --> TilingExplicitWithParamsCompressionExplicit : void setCompressionType([String compressionType])

    note right of TilingNoneCompressionNone
        TilingNone = Tiling mode is not MODE_EXPLICIT (default: MODE_COPY_FROM_METADATA)
        TilingExplicit = Tiling MODE_EXPLICIT set, no tile params yet
        TilingExplicitWithParams = Tiling MODE_EXPLICIT set and setTiling called
        CompressionNone = Compression mode is not MODE_EXPLICIT
        CompressionExplicit = Compression MODE_EXPLICIT set, no type set yet
        CompressionExplicitWithType = Compression MODE_EXPLICIT set and setCompressionType called
    end note
