stateDiagram-v2
    [*] --> NotDisplayable : Window Window([Frame owner])
    [*] --> NotDisplayable : Window Window([Window owner])
    [*] --> NotDisplayable : Window Window([Window owner], [GraphicsConfiguration gc])

    NotDisplayable --> NotDisplayable : List<Image> getIconImages()
    NotDisplayable --> NotDisplayable : void setIconImages([List icons])
    NotDisplayable --> NotDisplayable : void setIconImage([Image image])
    NotDisplayable --> NotDisplayable : void addNotify()
    NotDisplayable --> Displayable : void pack()
    NotDisplayable --> NotDisplayable : void setMinimumSize([Dimension minimumSize])
    NotDisplayable --> NotDisplayable : void setSize([Dimension d])
    NotDisplayable --> NotDisplayable : void setSize([int width], [int height])
    NotDisplayable --> NotDisplayable : void setLocation([int x], [int y])
    NotDisplayable --> NotDisplayable : void setLocation([Point p])
    NotDisplayable --> NotDisplayable : void reshape([int x], [int y], [int width], [int height])
    NotDisplayable --> Visible : void setVisible([boolean b])
    NotDisplayable --> Visible : void show()
    NotDisplayable --> NotDisplayable : Toolkit getToolkit()
    NotDisplayable --> NotDisplayable : String getWarningString()
    NotDisplayable --> NotDisplayable : Locale getLocale()
    NotDisplayable --> NotDisplayable : InputContext getInputContext()
    NotDisplayable --> NotDisplayable : void setCursor([Cursor cursor])
    NotDisplayable --> NotDisplayable : Window getOwner()
    NotDisplayable --> NotDisplayable : Window[] getOwnedWindows()
    NotDisplayable --> NotDisplayable : void setModalExclusionType([Dialog.ModalExclusionType exclusionType])
    NotDisplayable --> NotDisplayable : Dialog.ModalExclusionType getModalExclusionType()
    NotDisplayable --> NotDisplayable : void addWindowListener([WindowListener l])
    NotDisplayable --> NotDisplayable : void addWindowStateListener([WindowStateListener l])
    NotDisplayable --> NotDisplayable : void addWindowFocusListener([WindowFocusListener l])
    NotDisplayable --> NotDisplayable : void removeWindowListener([WindowListener l])
    NotDisplayable --> NotDisplayable : void removeWindowStateListener([WindowStateListener l])
    NotDisplayable --> NotDisplayable : void removeWindowFocusListener([WindowFocusListener l])
    NotDisplayable --> NotDisplayable : WindowListener[] getWindowListeners()
    NotDisplayable --> NotDisplayable : WindowFocusListener[] getWindowFocusListeners()
    NotDisplayable --> NotDisplayable : WindowStateListener[] getWindowStateListeners()
    NotDisplayable --> NotDisplayable : void getListeners([Class T])
    NotDisplayable --> NotDisplayable : void processEvent([AWTEvent e])
    NotDisplayable --> NotDisplayable : void processWindowEvent([WindowEvent e])
    NotDisplayable --> NotDisplayable : void processWindowFocusEvent([WindowEvent e])
    NotDisplayable --> NotDisplayable : void processWindowStateEvent([WindowEvent e])
    NotDisplayable --> NotDisplayable : void setAlwaysOnTop([boolean alwaysOnTop])
    NotDisplayable --> NotDisplayable : boolean isAlwaysOnTopSupported()
    NotDisplayable --> NotDisplayable : boolean isAlwaysOnTop()
    NotDisplayable --> NotDisplayable : Component getFocusOwner()
    NotDisplayable --> NotDisplayable : Component getMostRecentFocusOwner()
    NotDisplayable --> NotDisplayable : boolean isActive()
    NotDisplayable --> NotDisplayable : boolean isFocused()
    NotDisplayable --> NotDisplayable : Set<AWTKeyStroke> getFocusTraversalKeys([int id])
    NotDisplayable --> NotDisplayable : void setFocusCycleRoot([boolean focusCycleRoot])
    NotDisplayable --> NotDisplayable : boolean isFocusCycleRoot()
    NotDisplayable --> NotDisplayable : Container getFocusCycleRootAncestor()
    NotDisplayable --> NotDisplayable : boolean isFocusableWindow()
    NotDisplayable --> NotDisplayable : boolean getFocusableWindowState()
    NotDisplayable --> NotDisplayable : void setFocusableWindowState([boolean focusableWindowState])
    NotDisplayable --> NotDisplayable : void setAutoRequestFocus([boolean autoRequestFocus])
    NotDisplayable --> NotDisplayable : boolean isAutoRequestFocus()
    NotDisplayable --> NotDisplayable : void addPropertyChangeListener([PropertyChangeListener listener])
    NotDisplayable --> NotDisplayable : void addPropertyChangeListener([String propertyName], [PropertyChangeListener listener])
    NotDisplayable --> NotDisplayable : boolean isValidateRoot()
    NotDisplayable --> NotDisplayable : void postEvent([Event e])
    NotDisplayable --> NotDisplayable : boolean isShowing()
    NotDisplayable --> NotDisplayable : void applyResourceBundle([ResourceBundle rb])
    NotDisplayable --> NotDisplayable : void applyResourceBundle([String rbName])
    NotDisplayable --> NotDisplayable : void setType([Window.Type type])
    NotDisplayable --> NotDisplayable : Window.Type getType()
    NotDisplayable --> NotDisplayable : AccessibleContext getAccessibleContext()
    NotDisplayable --> NotDisplayable : void setLocationRelativeTo([Component c])
    NotDisplayable --> NotDisplayable : BufferStrategy getBufferStrategy()
    NotDisplayable --> NotDisplayable : void setLocationByPlatform([boolean locationByPlatform])
    NotDisplayable --> NotDisplayable : boolean isLocationByPlatform()
    NotDisplayable --> NotDisplayable : void setBounds([int x], [int y], [int width], [int height])
    NotDisplayable --> NotDisplayable : void setBounds([Rectangle r])
    NotDisplayable --> NotDisplayable : float getOpacity()
    NotDisplayable --> NotDisplayable : void setOpacity([float opacity])
    NotDisplayable --> NotDisplayable : Shape getShape()
    NotDisplayable --> NotDisplayable : void setShape([Shape shape])
    NotDisplayable --> NotDisplayable : Color getBackground()
    NotDisplayable --> NotDisplayable : void setBackground([Color bgColor])
    NotDisplayable --> NotDisplayable : boolean isOpaque()
    NotDisplayable --> NotDisplayable : void paint([Graphics g])
    NotDisplayable --> NotDisplayable : void toFront()
    NotDisplayable --> NotDisplayable : void toBack()
    NotDisplayable --> NotDisplayable : void hide()
    NotDisplayable --> NotDisplayable : void dispose()

    Displayable --> Displayable : List<Image> getIconImages()
    Displayable --> Displayable : void setIconImages([List icons])
    Displayable --> Displayable : void setIconImage([Image image])
    Displayable --> Displayable : void addNotify()
    Displayable --> Displayable : void pack()
    Displayable --> Displayable : void setMinimumSize([Dimension minimumSize])
    Displayable --> Displayable : void setSize([Dimension d])
    Displayable --> Displayable : void setSize([int width], [int height])
    Displayable --> Displayable : void setLocation([int x], [int y])
    Displayable --> Displayable : void setLocation([Point p])
    Displayable --> Displayable : void reshape([int x], [int y], [int width], [int height])
    Displayable --> Visible : void setVisible([boolean b])
    Displayable --> Visible : void show()
    Displayable --> NotDisplayable : void dispose()
    Displayable --> Displayable : Toolkit getToolkit()
    Displayable --> Displayable : String getWarningString()
    Displayable --> Displayable : Locale getLocale()
    Displayable --> Displayable : InputContext getInputContext()
    Displayable --> Displayable : void setCursor([Cursor cursor])
    Displayable --> Displayable : Window getOwner()
    Displayable --> Displayable : Window[] getOwnedWindows()
    Displayable --> Displayable : void setModalExclusionType([Dialog.ModalExclusionType exclusionType])
    Displayable --> Displayable : Dialog.ModalExclusionType getModalExclusionType()
    Displayable --> Displayable : void addWindowListener([WindowListener l])
    Displayable --> Displayable : void addWindowStateListener([WindowStateListener l])
    Displayable --> Displayable : void addWindowFocusListener([WindowFocusListener l])
    Displayable --> Displayable : void removeWindowListener([WindowListener l])
    Displayable --> Displayable : void removeWindowStateListener([WindowStateListener l])
    Displayable --> Displayable : void removeWindowFocusListener([WindowFocusListener l])
    Displayable --> Displayable : WindowListener[] getWindowListeners()
    Displayable --> Displayable : WindowFocusListener[] getWindowFocusListeners()
    Displayable --> Displayable : WindowStateListener[] getWindowStateListeners()
    Displayable --> Displayable : void getListeners([Class T])
    Displayable --> Displayable : void processEvent([AWTEvent e])
    Displayable --> Displayable : void processWindowEvent([WindowEvent e])
    Displayable --> Displayable : void processWindowFocusEvent([WindowEvent e])
    Displayable --> Displayable : void processWindowStateEvent([WindowEvent e])
    Displayable --> Displayable : void setAlwaysOnTop([boolean alwaysOnTop])
    Displayable --> Displayable : boolean isAlwaysOnTopSupported()
    Displayable --> Displayable : boolean isAlwaysOnTop()
    Displayable --> Displayable : Component getFocusOwner()
    Displayable --> Displayable : Component getMostRecentFocusOwner()
    Displayable --> Displayable : boolean isActive()
    Displayable --> Displayable : boolean isFocused()
    Displayable --> Displayable : Set<AWTKeyStroke> getFocusTraversalKeys([int id])
    Displayable --> Displayable : void setFocusCycleRoot([boolean focusCycleRoot])
    Displayable --> Displayable : boolean isFocusCycleRoot()
    Displayable --> Displayable : Container getFocusCycleRootAncestor()
    Displayable --> Displayable : boolean isFocusableWindow()
    Displayable --> Displayable : boolean getFocusableWindowState()
    Displayable --> Displayable : void setFocusableWindowState([boolean focusableWindowState])
    Displayable --> Displayable : void setAutoRequestFocus([boolean autoRequestFocus])
    Displayable --> Displayable : boolean isAutoRequestFocus()
    Displayable --> Displayable : void addPropertyChangeListener([PropertyChangeListener listener])
    Displayable --> Displayable : void addPropertyChangeListener([String propertyName], [PropertyChangeListener listener])
    Displayable --> Displayable : boolean isValidateRoot()
    Displayable --> Displayable : void postEvent([Event e])
    Displayable --> Displayable : boolean isShowing()
    Displayable --> Displayable : void applyResourceBundle([ResourceBundle rb])
    Displayable --> Displayable : void applyResourceBundle([String rbName])
    Displayable --> Displayable : Window.Type getType()
    Displayable --> Displayable : AccessibleContext getAccessibleContext()
    Displayable --> Displayable : void setLocationRelativeTo([Component c])
    Displayable --> Displayable : void createBufferStrategy([int numBuffers])
    Displayable --> Displayable : void createBufferStrategy([int numBuffers], [BufferCapabilities caps])
    Displayable --> Displayable : BufferStrategy getBufferStrategy()
    Displayable --> Displayable : void setLocationByPlatform([boolean locationByPlatform])
    Displayable --> Displayable : boolean isLocationByPlatform()
    Displayable --> Displayable : void setBounds([int x], [int y], [int width], [int height])
    Displayable --> Displayable : void setBounds([Rectangle r])
    Displayable --> Displayable : float getOpacity()
    Displayable --> Displayable : void setOpacity([float opacity])
    Displayable --> Displayable : Shape getShape()
    Displayable --> Displayable : void setShape([Shape shape])
    Displayable --> Displayable : Color getBackground()
    Displayable --> Displayable : void setBackground([Color bgColor])
    Displayable --> Displayable : boolean isOpaque()
    Displayable --> Displayable : void paint([Graphics g])
    Displayable --> Displayable : void toFront()
    Displayable --> Displayable : void toBack()
    Displayable --> Displayable : void hide()

    Visible --> Visible : List<Image> getIconImages()
    Visible --> Visible : void setIconImages([List icons])
    Visible --> Visible : void setIconImage([Image image])
    Visible --> Visible : void addNotify()
    Visible --> Visible : void pack()
    Visible --> Visible : void setMinimumSize([Dimension minimumSize])
    Visible --> Visible : void setSize([Dimension d])
    Visible --> Visible : void setSize([int width], [int height])
    Visible --> Visible : void setLocation([int x], [int y])
    Visible --> Visible : void setLocation([Point p])
    Visible --> Visible : void reshape([int x], [int y], [int width], [int height])
    Visible --> Displayable : void setVisible([boolean b])
    Visible --> Displayable : void hide()
    Visible --> NotDisplayable : void dispose()
    Visible --> Visible : Toolkit getToolkit()
    Visible --> Visible : String getWarningString()
    Visible --> Visible : Locale getLocale()
    Visible --> Visible : InputContext getInputContext()
    Visible --> Visible : void setCursor([Cursor cursor])
    Visible --> Visible : Window getOwner()
    Visible --> Visible : Window[] getOwnedWindows()
    Visible --> Visible : void setModalExclusionType([Dialog.ModalExclusionType exclusionType])
    Visible --> Visible : Dialog.ModalExclusionType getModalExclusionType()
    Visible --> Visible : void addWindowListener([WindowListener l])
    Visible --> Visible : void addWindowStateListener([WindowStateListener l])
    Visible --> Visible : void addWindowFocusListener([WindowFocusListener l])
    Visible --> Visible : void removeWindowListener([WindowListener l])
    Visible --> Visible : void removeWindowStateListener([WindowStateListener l])
    Visible --> Visible : void removeWindowFocusListener([WindowFocusListener l])
    Visible --> Visible : WindowListener[] getWindowListeners()
    Visible --> Visible : WindowFocusListener[] getWindowFocusListeners()
    Visible --> Visible : WindowStateListener[] getWindowStateListeners()
    Visible --> Visible : void getListeners([Class T])
    Visible --> Visible : void processEvent([AWTEvent e])
    Visible --> Visible : void processWindowEvent([WindowEvent e])
    Visible --> Visible : void processWindowFocusEvent([WindowEvent e])
    Visible --> Visible : void processWindowStateEvent([WindowEvent e])
    Visible --> Visible : void setAlwaysOnTop([boolean alwaysOnTop])
    Visible --> Visible : boolean isAlwaysOnTopSupported()
    Visible --> Visible : boolean isAlwaysOnTop()
    Visible --> Visible : Component getFocusOwner()
    Visible --> Visible : Component getMostRecentFocusOwner()
    Visible --> Visible : boolean isActive()
    Visible --> Visible : boolean isFocused()
    Visible --> Visible : Set<AWTKeyStroke> getFocusTraversalKeys([int id])
    Visible --> Visible : void setFocusCycleRoot([boolean focusCycleRoot])
    Visible --> Visible : boolean isFocusCycleRoot()
    Visible --> Visible : Container getFocusCycleRootAncestor()
    Visible --> Visible : boolean isFocusableWindow()
    Visible --> Visible : boolean getFocusableWindowState()
    Visible --> Visible : void setFocusableWindowState([boolean focusableWindowState])
    Visible --> Visible : void setAutoRequestFocus([boolean autoRequestFocus])
    Visible --> Visible : boolean isAutoRequestFocus()
    Visible --> Visible : void addPropertyChangeListener([PropertyChangeListener listener])
    Visible --> Visible : void addPropertyChangeListener([String propertyName], [PropertyChangeListener listener])
    Visible --> Visible : boolean isValidateRoot()
    Visible --> Visible : void postEvent([Event e])
    Visible --> Visible : boolean isShowing()
    Visible --> Visible : void applyResourceBundle([ResourceBundle rb])
    Visible --> Visible : void applyResourceBundle([String rbName])
    Visible --> Visible : Window.Type getType()
    Visible --> Visible : AccessibleContext getAccessibleContext()
    Visible --> Visible : void setLocationRelativeTo([Component c])
    Visible --> Visible : void createBufferStrategy([int numBuffers])
    Visible --> Visible : void createBufferStrategy([int numBuffers], [BufferCapabilities caps])
    Visible --> Visible : BufferStrategy getBufferStrategy()
    Visible --> Visible : boolean isLocationByPlatform()
    Visible --> Visible : void setBounds([int x], [int y], [int width], [int height])
    Visible --> Visible : void setBounds([Rectangle r])
    Visible --> Visible : float getOpacity()
    Visible --> Visible : void setOpacity([float opacity])
    Visible --> Visible : Shape getShape()
    Visible --> Visible : void setShape([Shape shape])
    Visible --> Visible : Color getBackground()
    Visible --> Visible : void setBackground([Color bgColor])
    Visible --> Visible : boolean isOpaque()
    Visible --> Visible : void paint([Graphics g])
    Visible --> Visible : void toFront()
    Visible --> Visible : void toBack()
    Visible --> Visible : void show()

    note right of NotDisplayable
        setType() only valid in NotDisplayable state.
        createBufferStrategy() requires Displayable or Visible.
        setLocationByPlatform(true) forbidden when Visible.
    end note

    note right of Visible
        dispose() returns window to NotDisplayable.
        Window can be re-shown after dispose() via pack() or show().
    end note
