stateDiagram-v2
    [*] --> AllowsChildren : DefaultMutableTreeNode DefaultMutableTreeNode()
    [*] --> AllowsChildren : DefaultMutableTreeNode DefaultMutableTreeNode([Object userObject])
    [*] --> MaybeAllowsChildren : DefaultMutableTreeNode DefaultMutableTreeNode([Object userObject], [boolean allowsChildren])

    AllowsChildren --> AllowsChildren : void insert([MutableTreeNode newChild], [int childIndex])
    AllowsChildren --> AllowsChildren : void remove([MutableTreeNode aChild])
    AllowsChildren --> AllowsChildren : void remove([int childIndex])
    AllowsChildren --> AllowsChildren : void removeAllChildren()
    AllowsChildren --> AllowsChildren : void add([MutableTreeNode newChild])
    AllowsChildren --> AllowsChildren : void setParent([MutableTreeNode newParent])
    AllowsChildren --> AllowsChildren : void setUserObject([Object userObject])
    AllowsChildren --> AllowsChildren : void removeFromParent()
    AllowsChildren --> AllowsChildren : TreeNode getParent()
    AllowsChildren --> AllowsChildren : TreeNode getChildAt([int index])
    AllowsChildren --> AllowsChildren : int getChildCount()
    AllowsChildren --> AllowsChildren : int getIndex([TreeNode aChild])
    AllowsChildren --> AllowsChildren : Enumeration<TreeNode> children()
    AllowsChildren --> AllowsChildren : boolean getAllowsChildren()
    AllowsChildren --> AllowsChildren : Object getUserObject()
    AllowsChildren --> AllowsChildren : boolean isNodeAncestor([TreeNode anotherNode])
    AllowsChildren --> AllowsChildren : boolean isNodeDescendant([DefaultMutableTreeNode anotherNode])
    AllowsChildren --> AllowsChildren : TreeNode getSharedAncestor([DefaultMutableTreeNode aNode])
    AllowsChildren --> AllowsChildren : boolean isNodeRelated([DefaultMutableTreeNode aNode])
    AllowsChildren --> AllowsChildren : int getDepth()
    AllowsChildren --> AllowsChildren : int getLevel()
    AllowsChildren --> AllowsChildren : TreeNode[] getPath()
    AllowsChildren --> AllowsChildren : TreeNode[] getPathToRoot([TreeNode aNode], [int depth])
    AllowsChildren --> AllowsChildren : Object[] getUserObjectPath()
    AllowsChildren --> AllowsChildren : TreeNode getRoot()
    AllowsChildren --> AllowsChildren : boolean isRoot()
    AllowsChildren --> AllowsChildren : DefaultMutableTreeNode getNextNode()
    AllowsChildren --> AllowsChildren : DefaultMutableTreeNode getPreviousNode()
    AllowsChildren --> AllowsChildren : Enumeration<TreeNode> preorderEnumeration()
    AllowsChildren --> AllowsChildren : Enumeration<TreeNode> postorderEnumeration()
    AllowsChildren --> AllowsChildren : Enumeration<TreeNode> breadthFirstEnumeration()
    AllowsChildren --> AllowsChildren : Enumeration<TreeNode> depthFirstEnumeration()
    AllowsChildren --> AllowsChildren : Enumeration<TreeNode> pathFromAncestorEnumeration([TreeNode ancestor])
    AllowsChildren --> AllowsChildren : boolean isNodeChild([TreeNode aNode])
    AllowsChildren --> AllowsChildren : TreeNode getFirstChild()
    AllowsChildren --> AllowsChildren : TreeNode getLastChild()
    AllowsChildren --> AllowsChildren : TreeNode getChildAfter([TreeNode aChild])
    AllowsChildren --> AllowsChildren : TreeNode getChildBefore([TreeNode aChild])
    AllowsChildren --> AllowsChildren : boolean isNodeSibling([TreeNode anotherNode])
    AllowsChildren --> AllowsChildren : int getSiblingCount()
    AllowsChildren --> AllowsChildren : DefaultMutableTreeNode getNextSibling()
    AllowsChildren --> AllowsChildren : DefaultMutableTreeNode getPreviousSibling()
    AllowsChildren --> AllowsChildren : boolean isLeaf()
    AllowsChildren --> AllowsChildren : DefaultMutableTreeNode getFirstLeaf()
    AllowsChildren --> AllowsChildren : DefaultMutableTreeNode getLastLeaf()
    AllowsChildren --> AllowsChildren : DefaultMutableTreeNode getNextLeaf()
    AllowsChildren --> AllowsChildren : DefaultMutableTreeNode getPreviousLeaf()
    AllowsChildren --> AllowsChildren : int getLeafCount()
    AllowsChildren --> AllowsChildren : String toString()
    AllowsChildren --> AllowsChildren : Object clone()
    AllowsChildren --> DoesNotAllowChildren : void setAllowsChildren([boolean allows])

    DoesNotAllowChildren --> DoesNotAllowChildren : void remove([MutableTreeNode aChild])
    DoesNotAllowChildren --> DoesNotAllowChildren : void remove([int childIndex])
    DoesNotAllowChildren --> DoesNotAllowChildren : void removeAllChildren()
    DoesNotAllowChildren --> DoesNotAllowChildren : void setParent([MutableTreeNode newParent])
    DoesNotAllowChildren --> DoesNotAllowChildren : void setUserObject([Object userObject])
    DoesNotAllowChildren --> DoesNotAllowChildren : void removeFromParent()
    DoesNotAllowChildren --> DoesNotAllowChildren : TreeNode getParent()
    DoesNotAllowChildren --> DoesNotAllowChildren : TreeNode getChildAt([int index])
    DoesNotAllowChildren --> DoesNotAllowChildren : int getChildCount()
    DoesNotAllowChildren --> DoesNotAllowChildren : int getIndex([TreeNode aChild])
    DoesNotAllowChildren --> DoesNotAllowChildren : Enumeration<TreeNode> children()
    DoesNotAllowChildren --> DoesNotAllowChildren : boolean getAllowsChildren()
    DoesNotAllowChildren --> DoesNotAllowChildren : Object getUserObject()
    DoesNotAllowChildren --> DoesNotAllowChildren : boolean isNodeAncestor([TreeNode anotherNode])
    DoesNotAllowChildren --> DoesNotAllowChildren : boolean isNodeDescendant([DefaultMutableTreeNode anotherNode])
    DoesNotAllowChildren --> DoesNotAllowChildren : TreeNode getSharedAncestor([DefaultMutableTreeNode aNode])
    DoesNotAllowChildren --> DoesNotAllowChildren : boolean isNodeRelated([DefaultMutableTreeNode aNode])
    DoesNotAllowChildren --> DoesNotAllowChildren : int getDepth()
    DoesNotAllowChildren --> DoesNotAllowChildren : int getLevel()
    DoesNotAllowChildren --> DoesNotAllowChildren : TreeNode[] getPath()
    DoesNotAllowChildren --> DoesNotAllowChildren : TreeNode[] getPathToRoot([TreeNode aNode], [int depth])
    DoesNotAllowChildren --> DoesNotAllowChildren : Object[] getUserObjectPath()
    DoesNotAllowChildren --> DoesNotAllowChildren : TreeNode getRoot()
    DoesNotAllowChildren --> DoesNotAllowChildren : boolean isRoot()
    DoesNotAllowChildren --> DoesNotAllowChildren : DefaultMutableTreeNode getNextNode()
    DoesNotAllowChildren --> DoesNotAllowChildren : DefaultMutableTreeNode getPreviousNode()
    DoesNotAllowChildren --> DoesNotAllowChildren : Enumeration<TreeNode> preorderEnumeration()
    DoesNotAllowChildren --> DoesNotAllowChildren : Enumeration<TreeNode> postorderEnumeration()
    DoesNotAllowChildren --> DoesNotAllowChildren : Enumeration<TreeNode> breadthFirstEnumeration()
    DoesNotAllowChildren --> DoesNotAllowChildren : Enumeration<TreeNode> depthFirstEnumeration()
    DoesNotAllowChildren --> DoesNotAllowChildren : Enumeration<TreeNode> pathFromAncestorEnumeration([TreeNode ancestor])
    DoesNotAllowChildren --> DoesNotAllowChildren : boolean isNodeChild([TreeNode aNode])
    DoesNotAllowChildren --> DoesNotAllowChildren : TreeNode getFirstChild()
    DoesNotAllowChildren --> DoesNotAllowChildren : TreeNode getLastChild()
    DoesNotAllowChildren --> DoesNotAllowChildren : TreeNode getChildAfter([TreeNode aChild])
    DoesNotAllowChildren --> DoesNotAllowChildren : TreeNode getChildBefore([TreeNode aChild])
    DoesNotAllowChildren --> DoesNotAllowChildren : boolean isNodeSibling([TreeNode anotherNode])
    DoesNotAllowChildren --> DoesNotAllowChildren : int getSiblingCount()
    DoesNotAllowChildren --> DoesNotAllowChildren : DefaultMutableTreeNode getNextSibling()
    DoesNotAllowChildren --> DoesNotAllowChildren : DefaultMutableTreeNode getPreviousSibling()
    DoesNotAllowChildren --> DoesNotAllowChildren : boolean isLeaf()
    DoesNotAllowChildren --> DoesNotAllowChildren : DefaultMutableTreeNode getFirstLeaf()
    DoesNotAllowChildren --> DoesNotAllowChildren : DefaultMutableTreeNode getLastLeaf()
    DoesNotAllowChildren --> DoesNotAllowChildren : DefaultMutableTreeNode getNextLeaf()
    DoesNotAllowChildren --> DoesNotAllowChildren : DefaultMutableTreeNode getPreviousLeaf()
    DoesNotAllowChildren --> DoesNotAllowChildren : int getLeafCount()
    DoesNotAllowChildren --> DoesNotAllowChildren : String toString()
    DoesNotAllowChildren --> DoesNotAllowChildren : Object clone()
    DoesNotAllowChildren --> AllowsChildren : void setAllowsChildren([boolean allows])

    MaybeAllowsChildren --> MaybeAllowsChildren : void insert([MutableTreeNode newChild], [int childIndex])
    MaybeAllowsChildren --> MaybeAllowsChildren : void remove([MutableTreeNode aChild])
    MaybeAllowsChildren --> MaybeAllowsChildren : void remove([int childIndex])
    MaybeAllowsChildren --> MaybeAllowsChildren : void removeAllChildren()
    MaybeAllowsChildren --> MaybeAllowsChildren : void add([MutableTreeNode newChild])
    MaybeAllowsChildren --> MaybeAllowsChildren : void setParent([MutableTreeNode newParent])
    MaybeAllowsChildren --> MaybeAllowsChildren : void setUserObject([Object userObject])
    MaybeAllowsChildren --> MaybeAllowsChildren : void removeFromParent()
    MaybeAllowsChildren --> MaybeAllowsChildren : TreeNode getParent()
    MaybeAllowsChildren --> MaybeAllowsChildren : TreeNode getChildAt([int index])
    MaybeAllowsChildren --> MaybeAllowsChildren : int getChildCount()
    MaybeAllowsChildren --> MaybeAllowsChildren : int getIndex([TreeNode aChild])
    MaybeAllowsChildren --> MaybeAllowsChildren : Enumeration<TreeNode> children()
    MaybeAllowsChildren --> MaybeAllowsChildren : boolean getAllowsChildren()
    MaybeAllowsChildren --> MaybeAllowsChildren : Object getUserObject()
    MaybeAllowsChildren --> MaybeAllowsChildren : boolean isNodeAncestor([TreeNode anotherNode])
    MaybeAllowsChildren --> MaybeAllowsChildren : boolean isNodeDescendant([DefaultMutableTreeNode anotherNode])
    MaybeAllowsChildren --> MaybeAllowsChildren : TreeNode getSharedAncestor([DefaultMutableTreeNode aNode])
    MaybeAllowsChildren --> MaybeAllowsChildren : boolean isNodeRelated([DefaultMutableTreeNode aNode])
    MaybeAllowsChildren --> MaybeAllowsChildren : int getDepth()
    MaybeAllowsChildren --> MaybeAllowsChildren : int getLevel()
    MaybeAllowsChildren --> MaybeAllowsChildren : TreeNode[] getPath()
    MaybeAllowsChildren --> MaybeAllowsChildren : TreeNode[] getPathToRoot([TreeNode aNode], [int depth])
    MaybeAllowsChildren --> MaybeAllowsChildren : Object[] getUserObjectPath()
    MaybeAllowsChildren --> MaybeAllowsChildren : TreeNode getRoot()
    MaybeAllowsChildren --> MaybeAllowsChildren : boolean isRoot()
    MaybeAllowsChildren --> MaybeAllowsChildren : DefaultMutableTreeNode getNextNode()
    MaybeAllowsChildren --> MaybeAllowsChildren : DefaultMutableTreeNode getPreviousNode()
    MaybeAllowsChildren --> MaybeAllowsChildren : Enumeration<TreeNode> preorderEnumeration()
    MaybeAllowsChildren --> MaybeAllowsChildren : Enumeration<TreeNode> postorderEnumeration()
    MaybeAllowsChildren --> MaybeAllowsChildren : Enumeration<TreeNode> breadthFirstEnumeration()
    MaybeAllowsChildren --> MaybeAllowsChildren : Enumeration<TreeNode> depthFirstEnumeration()
    MaybeAllowsChildren --> MaybeAllowsChildren : Enumeration<TreeNode> pathFromAncestorEnumeration([TreeNode ancestor])
    MaybeAllowsChildren --> MaybeAllowsChildren : boolean isNodeChild([TreeNode aNode])
    MaybeAllowsChildren --> MaybeAllowsChildren : TreeNode getFirstChild()
    MaybeAllowsChildren --> MaybeAllowsChildren : TreeNode getLastChild()
    MaybeAllowsChildren --> MaybeAllowsChildren : TreeNode getChildAfter([TreeNode aChild])
    MaybeAllowsChildren --> MaybeAllowsChildren : TreeNode getChildBefore([TreeNode aChild])
    MaybeAllowsChildren --> MaybeAllowsChildren : boolean isNodeSibling([TreeNode anotherNode])
    MaybeAllowsChildren --> MaybeAllowsChildren : int getSiblingCount()
    MaybeAllowsChildren --> MaybeAllowsChildren : DefaultMutableTreeNode getNextSibling()
    MaybeAllowsChildren --> MaybeAllowsChildren : DefaultMutableTreeNode getPreviousSibling()
    MaybeAllowsChildren --> MaybeAllowsChildren : boolean isLeaf()
    MaybeAllowsChildren --> MaybeAllowsChildren : DefaultMutableTreeNode getFirstLeaf()
    MaybeAllowsChildren --> MaybeAllowsChildren : DefaultMutableTreeNode getLastLeaf()
    MaybeAllowsChildren --> MaybeAllowsChildren : DefaultMutableTreeNode getNextLeaf()
    MaybeAllowsChildren --> MaybeAllowsChildren : DefaultMutableTreeNode getPreviousLeaf()
    MaybeAllowsChildren --> MaybeAllowsChildren : int getLeafCount()
    MaybeAllowsChildren --> MaybeAllowsChildren : String toString()
    MaybeAllowsChildren --> MaybeAllowsChildren : Object clone()
    MaybeAllowsChildren --> AllowsChildren : void setAllowsChildren([boolean allows])

    note right of DoesNotAllowChildren
        insert() and add() throw IllegalStateException
        in this state (node does not allow children).
        setAllowsChildren(true) transitions back to AllowsChildren.
    end note

    note right of MaybeAllowsChildren
        Created via constructor with boolean allowsChildren param.
        Runtime value of allowsChildren not statically known.
        insert() and add() are permitted here (false negatives
        accepted to avoid false positives).
    end note
