stateDiagram-v2
    [*] --> NotDisplayable : Window([Frame owner])
    [*] --> NotDisplayable : Window([Window owner])
    [*] --> NotDisplayable : Window([Window owner], [GraphicsConfiguration gc])

    NotDisplayable --> NotDisplayable : void dispose()
    NotDisplayable --> NotDisplayable : void setIconImages([List icons])
    NotDisplayable --> NotDisplayable : void setIconImage([Image image])
    NotDisplayable --> NotDisplayable : void addNotify()
    NotDisplayable --> NotDisplayable : void setMinimumSize([Dimension minimumSize])
    NotDisplayable --> NotDisplayable : void setSize([int width], [int height])
    NotDisplayable --> NotDisplayable : void setSize([Dimension d])
    NotDisplayable --> NotDisplayable : void setLocation([int x], [int y])
    NotDisplayable --> NotDisplayable : void setLocation([Point p])
    NotDisplayable --> NotDisplayable : void reshape([int x], [int y], [int width], [int height])
    NotDisplayable --> NotDisplayable : void setType([Window.Type type])
    NotDisplayable --> NotDisplayable : void setCursor([Cursor cursor])
    NotDisplayable --> NotDisplayable : void setModalExclusionType([Dialog.ModalExclusionType exclusionType])
    NotDisplayable --> NotDisplayable : void addWindowListener([WindowListener l])
    NotDisplayable --> NotDisplayable : void addWindowStateListener([WindowStateListener l])
    NotDisplayable --> NotDisplayable : void addWindowFocusListener([WindowFocusListener l])
    NotDisplayable --> NotDisplayable : void removeWindowListener([WindowListener l])
    NotDisplayable --> NotDisplayable : void removeWindowStateListener([WindowStateListener l])
    NotDisplayable --> NotDisplayable : void removeWindowFocusListener([WindowFocusListener l])
    NotDisplayable --> NotDisplayable : void setAlwaysOnTop([boolean alwaysOnTop])
    NotDisplayable --> NotDisplayable : void setFocusCycleRoot([boolean focusCycleRoot])
    NotDisplayable --> NotDisplayable : void setFocusableWindowState([boolean focusableWindowState])
    NotDisplayable --> NotDisplayable : void setAutoRequestFocus([boolean autoRequestFocus])
    NotDisplayable --> NotDisplayable : void addPropertyChangeListener([String propertyName], [PropertyChangeListener listener])
    NotDisplayable --> NotDisplayable : void addPropertyChangeListener([PropertyChangeListener listener])
    NotDisplayable --> NotDisplayable : void setLocationByPlatform([boolean locationByPlatform])
    NotDisplayable --> NotDisplayable : void setBounds([int x], [int y], [int width], [int height])
    NotDisplayable --> NotDisplayable : void setBounds([Rectangle r])
    NotDisplayable --> NotDisplayable : void setOpacity([float opacity])
    NotDisplayable --> NotDisplayable : void setShape([Shape shape])
    NotDisplayable --> NotDisplayable : void setBackground([Color bgColor])
    NotDisplayable --> NotDisplayable : void setLocationRelativeTo([Component c])
    NotDisplayable --> NotDisplayable : void applyResourceBundle([String rbName])
    NotDisplayable --> NotDisplayable : void applyResourceBundle([ResourceBundle rb])
    NotDisplayable --> NotDisplayable : void processEvent([AWTEvent e])
    NotDisplayable --> NotDisplayable : void processWindowEvent([WindowEvent e])
    NotDisplayable --> NotDisplayable : void processWindowFocusEvent([WindowEvent e])
    NotDisplayable --> NotDisplayable : void processWindowStateEvent([WindowEvent e])
    NotDisplayable --> NotDisplayable : void paint([Graphics g])
    NotDisplayable --> NotDisplayable : List<Image> getIconImages()
    NotDisplayable --> NotDisplayable : Toolkit getToolkit()
    NotDisplayable --> NotDisplayable : String getWarningString()
    NotDisplayable --> NotDisplayable : Locale getLocale()
    NotDisplayable --> NotDisplayable : InputContext getInputContext()
    NotDisplayable --> NotDisplayable : Window getOwner()
    NotDisplayable --> NotDisplayable : Window[] getOwnedWindows()
    NotDisplayable --> NotDisplayable : Dialog.ModalExclusionType getModalExclusionType()
    NotDisplayable --> NotDisplayable : WindowListener[] getWindowListeners()
    NotDisplayable --> NotDisplayable : WindowFocusListener[] getWindowFocusListeners()
    NotDisplayable --> NotDisplayable : WindowStateListener[] getWindowStateListeners()
    NotDisplayable --> NotDisplayable : void getListeners([Class T])
    NotDisplayable --> NotDisplayable : boolean isAlwaysOnTopSupported()
    NotDisplayable --> NotDisplayable : boolean isAlwaysOnTop()
    NotDisplayable --> NotDisplayable : Component getFocusOwner()
    NotDisplayable --> NotDisplayable : Component getMostRecentFocusOwner()
    NotDisplayable --> NotDisplayable : boolean isActive()
    NotDisplayable --> NotDisplayable : boolean isFocused()
    NotDisplayable --> NotDisplayable : Set<AWTKeyStroke> getFocusTraversalKeys([int id])
    NotDisplayable --> NotDisplayable : boolean isFocusCycleRoot()
    NotDisplayable --> NotDisplayable : Container getFocusCycleRootAncestor()
    NotDisplayable --> NotDisplayable : boolean isFocusableWindow()
    NotDisplayable --> NotDisplayable : boolean getFocusableWindowState()
    NotDisplayable --> NotDisplayable : boolean isAutoRequestFocus()
    NotDisplayable --> NotDisplayable : boolean isValidateRoot()
    NotDisplayable --> NotDisplayable : void postEvent([Event e])
    NotDisplayable --> NotDisplayable : boolean isShowing()
    NotDisplayable --> NotDisplayable : Window.Type getType()
    NotDisplayable --> NotDisplayable : AccessibleContext getAccessibleContext()
    NotDisplayable --> NotDisplayable : BufferStrategy getBufferStrategy()
    NotDisplayable --> NotDisplayable : boolean isLocationByPlatform()
    NotDisplayable --> NotDisplayable : float getOpacity()
    NotDisplayable --> NotDisplayable : Shape getShape()
    NotDisplayable --> NotDisplayable : Color getBackground()
    NotDisplayable --> NotDisplayable : boolean isOpaque()

    NotDisplayable --> Displayable : void pack()
    NotDisplayable --> Visible : void show()
    NotDisplayable --> Visible : void setVisible([boolean b])

    Displayable --> Displayable : void setIconImages([List icons])
    Displayable --> Displayable : void setIconImage([Image image])
    Displayable --> Displayable : void addNotify()
    Displayable --> Displayable : void setMinimumSize([Dimension minimumSize])
    Displayable --> Displayable : void setSize([int width], [int height])
    Displayable --> Displayable : void setSize([Dimension d])
    Displayable --> Displayable : void setLocation([int x], [int y])
    Displayable --> Displayable : void setLocation([Point p])
    Displayable --> Displayable : void reshape([int x], [int y], [int width], [int height])
    Displayable --> Displayable : void setCursor([Cursor cursor])
    Displayable --> Displayable : void setModalExclusionType([Dialog.ModalExclusionType exclusionType])
    Displayable --> Displayable : void addWindowListener([WindowListener l])
    Displayable --> Displayable : void addWindowStateListener([WindowStateListener l])
    Displayable --> Displayable : void addWindowFocusListener([WindowFocusListener l])
    Displayable --> Displayable : void removeWindowListener([WindowListener l])
    Displayable --> Displayable : void removeWindowStateListener([WindowStateListener l])
    Displayable --> Displayable : void removeWindowFocusListener([WindowFocusListener l])
    Displayable --> Displayable : void setAlwaysOnTop([boolean alwaysOnTop])
    Displayable --> Displayable : void setFocusCycleRoot([boolean focusCycleRoot])
    Displayable --> Displayable : void setFocusableWindowState([boolean focusableWindowState])
    Displayable --> Displayable : void setAutoRequestFocus([boolean autoRequestFocus])
    Displayable --> Displayable : void addPropertyChangeListener([String propertyName], [PropertyChangeListener listener])
    Displayable --> Displayable : void addPropertyChangeListener([PropertyChangeListener listener])
    Displayable --> Displayable : void setLocationByPlatform([boolean locationByPlatform])
    Displayable --> Displayable : void setBounds([int x], [int y], [int width], [int height])
    Displayable --> Displayable : void setBounds([Rectangle r])
    Displayable --> Displayable : void setOpacity([float opacity])
    Displayable --> Displayable : void setShape([Shape shape])
    Displayable --> Displayable : void setBackground([Color bgColor])
    Displayable --> Displayable : void setLocationRelativeTo([Component c])
    Displayable --> Displayable : void applyResourceBundle([String rbName])
    Displayable --> Displayable : void applyResourceBundle([ResourceBundle rb])
    Displayable --> Displayable : void processEvent([AWTEvent e])
    Displayable --> Displayable : void processWindowEvent([WindowEvent e])
    Displayable --> Displayable : void processWindowFocusEvent([WindowEvent e])
    Displayable --> Displayable : void processWindowStateEvent([WindowEvent e])
    Displayable --> Displayable : void paint([Graphics g])
    Displayable --> Displayable : void createBufferStrategy([int numBuffers], [BufferCapabilities caps])
    Displayable --> Displayable : void createBufferStrategy([int numBuffers])
    Displayable --> Displayable : List<Image> getIconImages()
    Displayable --> Displayable : Toolkit getToolkit()
    Displayable --> Displayable : String getWarningString()
    Displayable --> Displayable : Locale getLocale()
    Displayable --> Displayable : InputContext getInputContext()
    Displayable --> Displayable : Window getOwner()
    Displayable --> Displayable : Window[] getOwnedWindows()
    Displayable --> Displayable : Dialog.ModalExclusionType getModalExclusionType()
    Displayable --> Displayable : WindowListener[] getWindowListeners()
    Displayable --> Displayable : WindowFocusListener[] getWindowFocusListeners()
    Displayable --> Displayable : WindowStateListener[] getWindowStateListeners()
    Displayable --> Displayable : void getListeners([Class T])
    Displayable --> Displayable : boolean isAlwaysOnTopSupported()
    Displayable --> Displayable : boolean isAlwaysOnTop()
    Displayable --> Displayable : Component getFocusOwner()
    Displayable --> Displayable : Component getMostRecentFocusOwner()
    Displayable --> Displayable : boolean isActive()
    Displayable --> Displayable : boolean isFocused()
    Displayable --> Displayable : Set<AWTKeyStroke> getFocusTraversalKeys([int id])
    Displayable --> Displayable : boolean isFocusCycleRoot()
    Displayable --> Displayable : Container getFocusCycleRootAncestor()
    Displayable --> Displayable : boolean isFocusableWindow()
    Displayable --> Displayable : boolean getFocusableWindowState()
    Displayable --> Displayable : boolean isAutoRequestFocus()
    Displayable --> Displayable : boolean isValidateRoot()
    Displayable --> Displayable : void postEvent([Event e])
    Displayable --> Displayable : boolean isShowing()
    Displayable --> Displayable : Window.Type getType()
    Displayable --> Displayable : AccessibleContext getAccessibleContext()
    Displayable --> Displayable : BufferStrategy getBufferStrategy()
    Displayable --> Displayable : boolean isLocationByPlatform()
    Displayable --> Displayable : float getOpacity()
    Displayable --> Displayable : Shape getShape()
    Displayable --> Displayable : Color getBackground()
    Displayable --> Displayable : boolean isOpaque()

    Displayable --> NotDisplayable : void dispose()
    Displayable --> Visible : void show()
    Displayable --> Visible : void setVisible([boolean b])

    Visible --> Visible : void setIconImages([List icons])
    Visible --> Visible : void setIconImage([Image image])
    Visible --> Visible : void addNotify()
    Visible --> Visible : void setMinimumSize([Dimension minimumSize])
    Visible --> Visible : void setSize([int width], [int height])
    Visible --> Visible : void setSize([Dimension d])
    Visible --> Visible : void setLocation([int x], [int y])
    Visible --> Visible : void setLocation([Point p])
    Visible --> Visible : void reshape([int x], [int y], [int width], [int height])
    Visible --> Visible : void setCursor([Cursor cursor])
    Visible --> Visible : void setModalExclusionType([Dialog.ModalExclusionType exclusionType])
    Visible --> Visible : void addWindowListener([WindowListener l])
    Visible --> Visible : void addWindowStateListener([WindowStateListener l])
    Visible --> Visible : void addWindowFocusListener([WindowFocusListener l])
    Visible --> Visible : void removeWindowListener([WindowListener l])
    Visible --> Visible : void removeWindowStateListener([WindowStateListener l])
    Visible --> Visible : void removeWindowFocusListener([WindowFocusListener l])
    Visible --> Visible : void setAlwaysOnTop([boolean alwaysOnTop])
    Visible --> Visible : void setFocusCycleRoot([boolean focusCycleRoot])
    Visible --> Visible : void setFocusableWindowState([boolean focusableWindowState])
    Visible --> Visible : void setAutoRequestFocus([boolean autoRequestFocus])
    Visible --> Visible : void addPropertyChangeListener([String propertyName], [PropertyChangeListener listener])
    Visible --> Visible : void addPropertyChangeListener([PropertyChangeListener listener])
    Visible --> Visible : void setBounds([int x], [int y], [int width], [int height])
    Visible --> Visible : void setBounds([Rectangle r])
    Visible --> Visible : void setOpacity([float opacity])
    Visible --> Visible : void setShape([Shape shape])
    Visible --> Visible : void setBackground([Color bgColor])
    Visible --> Visible : void setLocationRelativeTo([Component c])
    Visible --> Visible : void applyResourceBundle([String rbName])
    Visible --> Visible : void applyResourceBundle([ResourceBundle rb])
    Visible --> Visible : void processEvent([AWTEvent e])
    Visible --> Visible : void processWindowEvent([WindowEvent e])
    Visible --> Visible : void processWindowFocusEvent([WindowEvent e])
    Visible --> Visible : void processWindowStateEvent([WindowEvent e])
    Visible --> Visible : void paint([Graphics g])
    Visible --> Visible : void toFront()
    Visible --> Visible : void toBack()
    Visible --> Visible : void createBufferStrategy([int numBuffers], [BufferCapabilities caps])
    Visible --> Visible : void createBufferStrategy([int numBuffers])
    Visible --> Visible : void pack()
    Visible --> Visible : void show()
    Visible --> Visible : void setVisible([boolean b])
    Visible --> Visible : List<Image> getIconImages()
    Visible --> Visible : Toolkit getToolkit()
    Visible --> Visible : String getWarningString()
    Visible --> Visible : Locale getLocale()
    Visible --> Visible : InputContext getInputContext()
    Visible --> Visible : Window getOwner()
    Visible --> Visible : Window[] getOwnedWindows()
    Visible --> Visible : Dialog.ModalExclusionType getModalExclusionType()
    Visible --> Visible : WindowListener[] getWindowListeners()
    Visible --> Visible : WindowFocusListener[] getWindowFocusListeners()
    Visible --> Visible : WindowStateListener[] getWindowStateListeners()
    Visible --> Visible : void getListeners([Class T])
    Visible --> Visible : boolean isAlwaysOnTopSupported()
    Visible --> Visible : boolean isAlwaysOnTop()
    Visible --> Visible : Component getFocusOwner()
    Visible --> Visible : Component getMostRecentFocusOwner()
    Visible --> Visible : boolean isActive()
    Visible --> Visible : boolean isFocused()
    Visible --> Visible : Set<AWTKeyStroke> getFocusTraversalKeys([int id])
    Visible --> Visible : boolean isFocusCycleRoot()
    Visible --> Visible : Container getFocusCycleRootAncestor()
    Visible --> Visible : boolean isFocusableWindow()
    Visible --> Visible : boolean getFocusableWindowState()
    Visible --> Visible : boolean isAutoRequestFocus()
    Visible --> Visible : boolean isValidateRoot()
    Visible --> Visible : void postEvent([Event e])
    Visible --> Visible : boolean isShowing()
    Visible --> Visible : Window.Type getType()
    Visible --> Visible : AccessibleContext getAccessibleContext()
    Visible --> Visible : BufferStrategy getBufferStrategy()
    Visible --> Visible : boolean isLocationByPlatform()
    Visible --> Visible : float getOpacity()
    Visible --> Visible : Shape getShape()
    Visible --> Visible : Color getBackground()
    Visible --> Visible : boolean isOpaque()

    Visible --> NotDisplayable : void dispose()
    Visible --> Displayable : void hide()

    note right of NotDisplayable
        setType() is only valid in this state.
        createBufferStrategy() throws IllegalStateException here.
        setLocationByPlatform(true) is allowed here.
    end note

    note right of Displayable
        setType() throws IllegalComponentStateException.
        createBufferStrategy() is valid here.
        setLocationByPlatform(true) is allowed here (window not showing).
    end note

    note right of Visible
        setType() throws IllegalComponentStateException.
        setLocationByPlatform(true) throws IllegalComponentStateException.
        toFront() and toBack() have effect only when visible.
    end note
