stateDiagram-v2
    [*] --> Created : PopupMenu PopupMenu()
    [*] --> Created : PopupMenu PopupMenu([String label])
    Created --> Created : void addNotify()
    Created --> Created : void show([Component origin], [int x], [int y])
    Created --> Created : AccessibleContext getAccessibleContext()
